# Generated by Django 5.1 on 2024-10-25 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventages_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Basic_suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_suppliers_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Company_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_img_url', models.ImageField(blank=True, null=True, upload_to='company_category')),
                ('category_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptive_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_options_name', models.CharField(max_length=128)),
                ('descriptive_options_img_url', models.ImageField(blank=True, null=True, upload_to='desciptive_options_img')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='House_pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_line_payment', models.BooleanField(default=False)),
                ('payment_by_night', models.BooleanField()),
                ('price_by_night', models.FloatField(default=0.0, null=True)),
                ('payment_by_week', models.BooleanField()),
                ('price_by_week', models.FloatField(default=0.0, null=True)),
                ('payment_by_month', models.BooleanField()),
                ('price_by_month', models.FloatField(default=0.0, null=True)),
                ('cancellation_price_available', models.BooleanField()),
                ('cancellation_price', models.FloatField(default=0.0, null=True)),
                ('for_sale_pricing', models.FloatField(default=0.0, null=True)),
                ('for_sale_pricing_discussed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Housing_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
                ('category_img_url', models.ImageField(blank=True, null=True, upload_to='UploadedImages/category_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Housing_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='UploadedImages/housing_img')),
            ],
        ),
        migrations.CreateModel(
            name='Included_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Nearest_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAndDistance', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Otp_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=128)),
                ('room_empty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='UploadedImages/room_img')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
                ('trial_days', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usefull_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefull_equipment_name', models.CharField(max_length=128)),
                ('usefull_equipment_img_url', models.ImageField(blank=True, null=True, upload_to='UploadedImages/usefull')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bref_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('municipality', models.CharField(max_length=128)),
                ('town', models.CharField(max_length=128)),
                ('postal_code', models.IntegerField()),
                ('map_long', models.FloatField()),
                ('map_lat', models.FloatField()),
                ('dimension', models.FloatField(null=True)),
                ('nb_people', models.IntegerField()),
                ('all_nb_bed', models.IntegerField()),
                ('nb_room', models.IntegerField()),
                ('total_nb_bath_room', models.IntegerField()),
                ('special_request', models.BooleanField(default=True)),
                ('room_in_hotel', models.BooleanField(default=False)),
                ('allow_child', models.BooleanField(default=True)),
                ('housing_empty', models.BooleanField(default=False)),
                ('given_documents', models.CharField(max_length=128, null=True)),
                ('housing_no', models.IntegerField(null=True)),
                ('housing_kind', models.CharField(max_length=50)),
                ('service_type', models.IntegerField()),
                ('direct_owner', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advantages_id', models.ManyToManyField(to='api.adventages')),
                ('basic_suppliers_id', models.ManyToManyField(to='api.basic_suppliers')),
                ('descriptive_options_id', models.ManyToManyField(to='api.descriptive_options')),
                ('house_pricing_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.house_pricing')),
                ('housing_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='api.housing_category')),
                ('housing_img_id', models.ManyToManyField(to='api.housing_img')),
                ('included_services_id', models.ManyToManyField(to='api.included_services')),
                ('nearest_location_id', models.ManyToManyField(to='api.nearest_location')),
            ],
        ),
        migrations.CreateModel(
            name='Housing_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.BooleanField()),
                ('reservation_for_you', models.BooleanField()),
                ('for_who_first_name', models.CharField(max_length=128, null=True)),
                ('for_who_last_name', models.CharField(max_length=128, null=True)),
                ('for_who_email', models.CharField(max_length=128, null=True)),
                ('for_who_phone_no', models.IntegerField(null=True)),
                ('nb_peaple', models.IntegerField()),
                ('nb_children', models.IntegerField()),
                ('duration', models.CharField(max_length=20, null=True)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('starting_hour', models.TimeField(blank=True, null=True)),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('un_know_duration', models.BooleanField()),
                ('ordered', models.BooleanField(default=False)),
                ('payment_choice', models.CharField(max_length=1, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('phone_no', models.IntegerField()),
                ('on_line_paiment', models.BooleanField(default=False)),
                ('order_accepted', models.BooleanField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('housing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.housing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('housing_order_id', models.ManyToManyField(to='api.housing_order')),
            ],
        ),
        migrations.CreateModel(
            name='Outstanding_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=128)),
                ('equipment_img_url', models.ImageField(blank=True, null=True, upload_to='UploadedImages/outstand')),
                ('equipment_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_category', to='api.equipments_category')),
            ],
        ),
        migrations.AddField(
            model_name='housing',
            name='outstanding_equipments_id',
            field=models.ManyToManyField(to='api.outstanding_equipment'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni_tof_url_one', models.ImageField(blank=True, null=True, upload_to='UploadedImages/CNI_TOP')),
                ('cni_tof_url_two', models.ImageField(blank=True, null=True, upload_to='UploadedImages/CNI_TOP')),
                ('subscribe_payment_resolved', models.BooleanField(default=False)),
                ('whoAreYou', models.BooleanField(default=False)),
                ('company_type', models.CharField(max_length=128, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='UploadedImages/user_profile_img')),
                ('phone_num', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('birth_data', models.DateTimeField(blank=True, null=True)),
                ('post', models.CharField(max_length=255, null=True)),
                ('web_site_url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manage_housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_accepted', models.BooleanField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('housing_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.housing_order')),
                ('provider_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
        ),
        migrations.AddField(
            model_name='housing',
            name='provider_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='api.provider'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('company_email', models.CharField(max_length=60)),
                ('company_phone_no', models.IntegerField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='UploadedImages/company_logo')),
                ('activity_sector', models.CharField(max_length=128)),
                ('nb_employees', models.IntegerField()),
                ('slogan', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('map_long', models.FloatField(default=0.0)),
                ('map_lat', models.FloatField(default=0.0)),
                ('banner_img_url', models.ImageField(blank=True, null=True, upload_to='UploadedImages/company_banner_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
        ),
        migrations.AddField(
            model_name='housing',
            name='room_id',
            field=models.ManyToManyField(related_name='housing', to='api.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_img_id',
            field=models.ManyToManyField(to='api.room_img'),
        ),
        migrations.CreateModel(
            name='Security_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=128)),
                ('equipment_image_url', models.ImageField(blank=True, null=True, upload_to='UploadedImages/security_equipment_img')),
                ('equipment_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_equipment', to='api.equipments_category')),
            ],
        ),
        migrations.AddField(
            model_name='housing',
            name='security_equipments_id',
            field=models.ManyToManyField(to='api.security_equipment'),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='housing',
            name='usefull_eq_id',
            field=models.ManyToManyField(to='api.usefull_equipment'),
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('sex', models.BooleanField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
