# Generated by Django 5.1 on 2024-10-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscribe_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user_id',
            new_name='user',
        ),
    ]
