# Generated by Django 5.1 on 2024-10-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_subscribe_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing_order',
            name='order_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
