

from django.contrib import admin
from django.urls import path
from . import views
from .views import GetHousingOrdersStats


urlpatterns = [
    path('get-admin-user/', views.GetAdminUser.as_view({'get': 'retrieve'}), name='equipments-create'),
    path('get-user/', views.GetUser.as_view({'get': 'retrieve'}), name='equipments-create'),
    # path('get-connected-user/', views.GetConnectedUser.as_view({'get': 'list', 'post': 'create'}), name='user-get'),
    path('create-equipments-categories/', views.EquipmentsCategoryCreate.as_view({'get': 'list', 'post': 'create'}), name='equipments-create'),
    path('create-equipments-categories/<int:pk>/', views.EquipmentsCategoryCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='equipments-update'),
    path('verify-otp-code/', views.VerifyOTP.as_view(), name='verify-otp'),
    path('request-new-otp/', views.RequestNewOTP.as_view(), name='request-new-otp'),
    path('forgotten-pass-new-otp/', views.ForgottenPasswd.as_view({'get': 'list', 'post': 'create'}), name='forgotten-new-otp'),
    path('update-password/<str:email>/', views.UpdatePassword.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='update-password'),
    path('create-housing-categories/', views.HousingCategoryCreate.as_view({'get': 'list', 'post': 'create'}), name='equipments-create'),
    path('get-stat-housing-categories/', views.HousingCategoryGet.as_view({'get': 'list', 'post': 'create'}), name='equipments-create'),
    path('create-housing-category/<int:pk>/', views.HousingCategoryCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='equipments-update'),
    path('create-housing-img/', views.HousingImgCreate.as_view({'get': 'list', 'post': 'create'}), name='housing-img-create'),
    path('create-housing-img/<int:pk>', views.HousingImgCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='housing-img-update'),
    path('create-outstanding-equipments/', views.OutstandingEquipmentsCreate.as_view({'get': 'list', 'post': 'create'}), name='outstanding-equipments-create'),
    path('create-outstanding-equipments/<int:pk>/', views.OutstandingEquipmentsCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='outstanding-equipments-create'),
    path('create-usefull-equipments/', views.UsefullEquipmentCreate.as_view({'get': 'list', 'post': 'create'}), name='usefull-equipments-create'),
    path('create-usefull-equipments/<int:pk>/', views.UsefullEquipmentCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='usefull-equipments-create'),
    path('create-included-services/', views.IncludedServicesCreate.as_view(), name='included-services-create'),
    path('get-included-services/<int:pk>/', views.IncludedServicesGet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='included-services-create'),
    path('create-basic-suppliers/', views.BasicSuppliersCreate.as_view({'get': 'list', 'post': 'create'}), name='basic-suppliers-create'),
    path('create-basic-suppliers/<int:pk>/', views.BasicSuppliersCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='basic-suppliers-create'),
    path('create-nearest-locations/', views.NearestLocationsCreate.as_view(), name='nearest-locations-create'),
    path('get-nearest-locations/<int:pk>/', views.NearestLocationsGet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='nearest-locations-create'),
    path('create-security-equipments/', views.SecurityEquipmentsCreate.as_view({'get': 'list', 'post': 'create'}), name='security-equipments-create'),
    path('create-security-equipments/<int:pk>/', views.SecurityEquipmentsCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='security-equipments-create'),
    path('create-descriptive-options/', views.DescriptiveOptionsCreate.as_view({'get': 'list', 'post': 'create'}), name='descriptive-options-create'),
    path('create-descriptive-options/<int:pk>/', views.DescriptiveOptionsCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='descriptive-options-update'),
    path('create-room-img/', views.RoomImgCreate.as_view(), name='room-img-create'),
    path('get-room-img/<int:pk>/', views.RoomGetImg.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='room-img-get'),
    path('create-advantages/', views.AdventagesCreate.as_view({'get': 'list', 'post': 'create'}), name='advantages-create'),
    path('create-advantages/<int:pk>/', views.AdventagesCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='advantages-create'),
    path('create-room/', views.RoomCreate.as_view(), name='room-create'),
    path('create-room/<int:pk>/', views.RoomCreate.as_view(), name='room-create'),
    path('get-room-detail/<int:pk>/', views.GetRoomDetail.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='room-get'),
    path('create-house-pricing/', views.HousePricingCreate.as_view({'get': 'list', 'post': 'create'}), name='house-pricing-create'),
    path('create-house-pricing/<int:pk>/', views.HousePricingCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='house-pricing-edit'),
    path('create-provider/', views.ProviderCreate.as_view(), name='provider-create'),
    path('edit-provider/<int:pk>/', views.ProviderEdit.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='provider-edit'),
    path('get-provider/', views.ProviderGet.as_view(), name='provider-create'),
    path('create-housing/', views.HousingCreate.as_view({'get': 'list', 'post': 'create'}), name='housing-create'),
    path('get-categoric-housing/<int:pk>/', views.GetCategoricHousing.as_view({'get': 'list', 'post': 'create'}), name='housing-create'),
    path('get-filtered-housing-category/<int:pk>/', views.HousingFilterCategory.as_view({'get': 'list', 'post': 'create'}), name='housing-filter-category'),
    path('get-filtered-housing-company/<int:pk>/', views.HousingFilterCompany.as_view({'get': 'list', 'post': 'create'}), name='housing-filter-category'),
    path('get-housing/', views.GetHousing.as_view({'get': 'list', 'post': 'create'}), name='housing-create'),
    path('create-housing/<int:pk>/', views.HousingCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='housing-edit'),
    path('create-company-category/', views.CompanyCategoryCreate.as_view(), name='company-category-create'),
    path('create-company/', views.CompanyCreate.as_view({'get': 'list', 'post': 'create'}), name='company-create'),
    path('get-company/', views.CompanyGet.as_view({'get': 'list', 'post': 'create'}), name='company-get'),
    path('get-company-all/', views.CompanyGetAll.as_view({'get': 'list', 'post': 'create'}), name='company-get-all'),
    path('get-company/<int:pk>/', views.CompanyGetSpecifics.as_view({'get': 'list', 'post': 'create'}), name='company-get-all'),
    path('create-housing-order/', views.HousingOrderCreate.as_view({'get': 'list', 'post': 'create'}), name='housing-order-create'),
    path('get-housing-order/', views.GetHousingOrders.as_view({'get': 'list', 'post': 'create'}), name='housing-order-create'),
    path('edit-housing-order-accepted/<int:pk>/', views.HousingOrderAccepted.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='housing-order-edit-accepted'),
    path('get-cart-order/', views.GetCartOrders.as_view({'get': 'list', 'post': 'create'}), name='cart-order-get'),
    path('get-ordred-housings/<int:pk>/', views.GetHousingOrdered.as_view({'get': 'list', 'post': 'create'}), name='housing-order-create'),
    path('get-completed-housings/<int:pk>/', views.HousingOrderCompleted.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='housing-completed-create'),
    path('get-refused-housings/<int:pk>/', views.HousingOrderOrderAccepted.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='housing-completed-create'),
    path('get-ordered-housings/<int:pk>/', views.HousingOrderOrdered.as_view({'put': 'update'}), name='housing-ordered-create'),
    # path('create-housing-order/<int:housing_id>/', views.HousingOrderCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='housing-order-edit'),
    path('create-card-create/', views.CardCreate.as_view({'get': 'list', 'post': 'create'}), name='card-create'),
    path('create-card-create/<int:pk>/', views.CardCreate.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='card-edit'),
    path('create-manage-housing/', views.ManageHousingCreate.as_view(), name='manage-housing-create'),
    path('create-subscribe/', views.SubscribeCreate.as_view(), name='subscribe-create'),
    path('create-user-info/', views.UserInfoCreate.as_view(), name='subscribe-create'),
    path('create-otpcode/', views.OtpCodeCreate.as_view(), name='otpcode-create'),
    path('create-subscription/', views.Subscription.as_view({'get': 'list', 'post': 'create'}), name='subscription-create'),
    path('get-subscription/<int:pk>/', views.Subscribers.as_view({'get': 'list', 'post': 'create'}), name='subscription-get'),
    path('get-subscribed-users/', views.SubscribedUsers.as_view({'get': 'list', 'post': 'create'}), name='subscription-get'),
    path('housing-order-stats/', GetHousingOrdersStats.as_view(), name='housing-order-stats'),
    path('monthly-housing-stats/', views.GetHousingStats.as_view({'get': 'list'}), name='housing-stats'),

]